### ISSUE TITLE
Restrict middleware execution to a certain path(s)

### ISSUE THREAD

**Issue by delvedor** [fastify/middie#1]
As titled: 
Related to https://github.com/fastify/fastify/issues/55

Could be a good idea implement this?
At a first look I don't think it will have a sensible impact on performances.

Example:
```js
fastify.use('/assets', serveStatic(`${__dirname}/dist`))
// could be an array of paths as well
fastify.use(['/assets', '/public'], serveStatic(`${__dirname}/dist`))
```

cc @mcollina @cedmax

**Comment by mcollina** [comment]
A first look is half a PR :)

**Comment by mujtabazaidi** [comment]
`fastify.use('/js', serveStatic(`${__dirname}/assets/js`));`

my js files are in /assets/js.

using in pug

script(type='text/javascript', src='/js/client.js')

but still getting 404.

**Comment by mcollina** [comment]
weird, can you upload a full example?

**Comment by mujtabazaidi** [comment]
// server.js
const fastify = require('fastify')();
const serveStatic = require('serve-static');

fastify.register(require('./routes/route'));

fastify.register(require('point-of-view'),{
  engine:{
    pug: require('pug')
  }
});

fastify.use('/js', serveStatic(`${__dirname}/assets/js`));  
fastify.use('/css', serveStatic(`${__dirname}/assets/css`));  

fastify.listen(8000, function (err) {
    if (err) throw err
    console.log(`server listening on ${fastify.server.address().port}`)
  }
);

// index.pug

html
    head    
        link(rel='stylesheet', type='text/css', href='/css/main.css')
        script(type='text/javascript', src='/js/client.js')
        
    body
        h1 WORLD!

**Comment by mcollina** [comment]
Confirmed.

**Comment by mujtabazaidi** [comment]
It's still not working. i am using it without middie.

**Comment by mcollina** [comment]
This was fixed in `middie` v2. It is going to land in the next release of fastify. See https://github.com/fastify/fastify/pull/170

**Comment by mujtabazaidi** [comment]
Hi i am using "fastify": "^0.28.0" and "middie": "^2.0.0"  but the issue with the same example given above remains same. isn't it merged in new release?

**Comment by mcollina** [comment]
@mujtabazaidi we have another thing do land in fastify for this: https://github.com/fastify/fastify/pull/266.

**Comment by mujtabazaidi** [comment]
@mcollina  sorry to delete my comment i thought it's issue on my side. so it's still not serving 

fastify.use('/assets', serveStatic(`${__dirname}/dist`))
// could be an array of paths as well
fastify.use(['/assets', '/public'], serveStatic(`${__dirname}/dist`))

this way? if yes then will it be landing in coming releases>
